# This template file should be left untouched
# The app will in order:
# 1. Read this file (template.config.toml)
# 2. Overwrite the settings with those in file config.toml (it it exists)
# 3. Overwrite the settings with environment variables called "TILE_INFLUX_<SECTION>_<KEY>" (with section and key uppercase), if these exist.
#    For example, set the env var TILE_INFLUX_MAIN_LOGVERBOSITY to DEBUG to overwrite the log verbosity


[tile]
username = "user@email.com"    # Tile's login.
password = "strong password"   # Tile's password.
include = []                   # List of uuid or name of Tile(s) to include. Ignored if empty.
exclude = []                   # List of uuid or name of Tile(s) to exclude. Ignored if empty.
warn_if_older_days = 3         # Warn (once) if this tile has no records newer than this amount of days

# Create org, bucket & token by navigating to your influx url from a browser
[influx]
url = "http://localhost:8086"  # Location of influxdb v2 server
bucket = "Life360"             # Name of available bucket
token = "super-secret-token"   # Token with write permission to bucket
org = "your org in influx"     # Org of the bucket
measurement = "location"       # Name to give to measurements
no_op = false                  # Set to true for testing, in which case connection is tested but records are not imported

[main]
log_verbosity = "INFO" # By increasing level of verbosity = FATAL, ERROR, WARNING, INFO, DEBUG.
loop_seconds  = 180    # Time to wait between two queries to Tile's backend. 0 to only query once

